export const ROUTES = {
  HOME: '/',
  CALCULATOR: '/calculator',
  INVENTORY: '/inventory',
  BLOCKS: '/blocks',
  SLABS: '/slabs',
  OFFCUTS: '/offcuts',
  MOVEMENTS: '/movements',
  PRODUCTION: '/production',
  MACHINES: '/machines',
  MAINTENANCE: '/maintenance',
  PURCHASES: '/purchases',
  SUPPLIERS: '/suppliers',
  CUSTOMERS: '/customers',
  QUOTATIONS: '/quotations',
  ORDERS: '/orders',
  WORKERS: '/workers',
  PARTNERS: '/partners',
  ATTENDANCE: '/attendance',
  PAYROLL: '/payroll',
  EXPENSES: '/expenses',
  UTILITIES: '/utilities',
  REPORTS: '/reports',
  NOTIFICATIONS: '/notifications',
  PRINT: '/print',
  ABOUT: '/about',
  SETTINGS: '/settings',
  LOGIN: '/login',
  // ── v2.4 expansion ──
  WORK_ORDERS: '/work-orders',
  GATE_PASSES: '/gate-passes',
  RECEIPTS: '/receipts',
  LEDGERS: '/ledgers',
  ACCOUNTING: '/accounting',
  VEHICLES: '/vehicles',
  CONSUMABLES: '/consumables',
  AGENTS: '/agents',
  PRICE_LISTS: '/price-lists',
  COMPLAINTS: '/complaints',
  INSTALLATION: '/installation',
  STOCK_COUNT: '/stock-count',
  AUDIT_LOG: '/audit-log',
  REPORT_BUILDER: '/report-builder',
  LOTS: '/lots',
}

export default ROUTES
