export const ROUTES = {
  HOME: '/',
  CALCULATOR: '/calculator',
  INVENTORY: '/inventory',
  BLOCKS: '/blocks',
  SLABS: '/slabs',
  OFFCUTS: '/offcuts',
  MOVEMENTS: '/movements',
  PRODUCTION: '/production',
  MACHINES: '/machines',
  MAINTENANCE: '/maintenance',
  PURCHASES: '/purchases',
  SUPPLIERS: '/suppliers',
  CUSTOMERS: '/customers',
  QUOTATIONS: '/quotations',
  ORDERS: '/orders',
  WORKERS: '/workers',
  PARTNERS: '/partners',
  ATTENDANCE: '/attendance',
  PAYROLL: '/payroll',
  EXPENSES: '/expenses',
  UTILITIES: '/utilities',
  REPORTS: '/reports',
  NOTIFICATIONS: '/notifications',
  PRINT: '/print',
  ABOUT: '/about',
  SETTINGS: '/settings',
  LOGIN: '/login',
}

export default ROUTES
