// All localStorage keys in one place — never scatter raw strings around the app.
const NS = 'marble'

const k = (name) => `${NS}.${name}`

export const STORAGE_KEYS = {
  LANG: k('lang'),
  THEME: k('theme'),
  URDU_DIGITS: k('urduDigits'),
  SIDEBAR: k('sidebar'),
  AUTH: k('auth'),
  USERS: k('users'),
  SETTINGS: k('settings'),
  COMPANY: k('company'),
  SYNC_QUEUE: k('syncQueue'),
  DELETED_QUEUE: k('deletedQueue'),
  DELETED_IDS: k('deletedIds'),
  LAST_SYNC: k('lastSync'),
  SEED_DONE: k('seedDone'),
  PRINT_REQUEST: k('printRequest'),

  // data collections
  BLOCKS: k('blocks'),
  SLABS: k('slabs'),
  OFFCUTS: k('offcuts'),
  MOVEMENTS: k('movements'),
  CUTTING_PLANS: k('cuttingPlans'),
  JOB_CARDS: k('jobCards'),
  MACHINES: k('machines'),
  MAINTENANCE: k('maintenance'),
  PURCHASES: k('purchases'),
  SUPPLIERS: k('suppliers'),
  CUSTOMERS: k('customers'),
  QUOTATIONS: k('quotations'),
  ORDERS: k('orders'),
  WORKERS: k('workers'),
  ATTENDANCE: k('attendance'),
  PIECEWORK: k('piecework'),
  PAYROLL: k('payroll'),
  EXPENSES: k('expenses'),
  PARTNERS: k('partners'),
  UTILITIES: k('utilities'),
  NOTIFICATIONS: k('notifications'),

  // ── v2.4 expansion — documents, accounting, operations, security ──
  WORK_ORDERS: k('workOrders'),
  GATE_PASSES: k('gatePasses'),
  RECEIPTS: k('receipts'),
  LEDGER_ENTRIES: k('ledgerEntries'),
  ACCOUNTS: k('accounts'),
  VOUCHERS: k('vouchers'),
  CREDIT_NOTES: k('creditNotes'),
  DEBIT_NOTES: k('debitNotes'),
  VEHICLES: k('vehicles'),
  TRIPS: k('trips'),
  CONSUMABLES: k('consumables'),
  CONSUMABLE_MOVES: k('consumableMoves'),
  AGENTS: k('agents'),
  COMMISSIONS: k('commissions'),
  PRICE_LISTS: k('priceLists'),
  COMPLAINTS: k('complaints'),
  RETURNS: k('returns'),
  GRN: k('grn'),
  INSTALLATION_JOBS: k('installationJobs'),
  STOCK_COUNTS: k('stockCounts'),
  AUDIT_LOG: k('auditLog'),
  FOLLOWUPS: k('followups'),
  BRANCHES: k('branches'),
  LOTS: k('lots'),
}

export default STORAGE_KEYS
